### ISSUE TITLE
Small suggestions

### ISSUE THREAD

**Issue by xuerongjie** [sneakyevil/SD-ModMenu#62]
Add manual loading
Add more practical things to make it more realistic.
I come from China. How can I sponsor your modifier

**Comment by sneakyevil** [comment]
May you explain what do you mean by "manual loading"?

**Comment by xuerongjie** [comment]
You will understand when you play CSGO. Manual reloading means that the player needs to click the R key to reload after all the bullets are shot. The protagonist in the game is automatic loading.

**Comment by sneakyevil** [comment]
The game already has manual reload functionality? 
![image](https://github.com/sneakyevil/SD-ModMenu/assets/29150970/06745013-f4c8-4adf-824a-de9d32986086)
And I been playing CSGO since it's release and there hasn't been any manual relaoding needed after all bullets has been shot. 
Also I wouldn't even initialize this as feature in Mod Menu since it's more like gameplay tweaker that would be more suitable in additional modification rather than Mod Menu, another note is that the game uses the reload gun functionality through action nodes, which might be near impossible to modify atm since there can be multiple stuff calling some condition that can be tied to multiple ActionNodes which can result in breaking whole Behaviour of some Player/Ped Actions.

**Comment by xuerongjie** [comment]
Most games don't have manual loading, but manual loading is more realistic. In blank ammunition, manual loading is necessary.
And how can I sponsor your modifier? I come from China and can't use foreign payment.



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 5, 2023 03:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sneakyevil/SD-ModMenu] Small suggestions (Issue #62)




 
The game already has manual reload functionality?
 
 And I been playing CSGO since it's release and there hasn't been any manual relaoding needed after all bullets has been shot.
 Also I wouldn't even initialize this as feature in Mod Menu since it's more like gameplay tweaker that would be more suitable in additional modification rather than Mod Menu, another note is that the game uses the reload gun functionality through action nodes, which might be near impossible to modify atm since there can be multiple stuff calling some condition that can be tied to multiple ActionNodes which can result in breaking whole Behaviour of some Player/Ped Actions.

**Comment by sneakyevil** [comment]
If you can't sponsor from China there is nothing I can do about it. I'm not the one responsible for the payment options that github sponsor is giving to users. I before tried to give ability for china people to donate me through Alipay, but alipay doesn't even allow me to link my card so I couldn't be able to even withdraw the money from it.

**Comment by xuerongjie** [comment]
It's too difficult. I want to use your latest version of the modifier. What should I do?



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 5, 2023 05:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sneakyevil/SD-ModMenu] Small suggestions (Issue #62)




 
If you can't sponsor from China there is nothing I can do about it. I'm not the one responsible for the payment options that github sponsor is giving to users. I before tried to give ability for china people to donate me through Alipay, but alipay doesn't even allow me to link my card so I couldn't be able to even withdraw the money from it.
